### PR TITLE
My Library App

### PR DESCRIPTION
**Pull request by Davidosky007**
## JS_LIBRARY
In this project
* A button was added to toggle each book's read status
* A button was added to remove each book from the library
* Books created were stored on the local storage

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work. 💻 👀 ✨ 
- Nice page design.
- Good work on the classes and methods.
- Good work implementing data persistence in your project.

## However, there are some changes required 👀 🧰 🔨 🔧 
- When I delete the second book in a list of 3 books, that causes *two* books to be deleted instead of just the one I wanted to delete. Please fix this bug.

**[OPTIONAL]**
- When I forget to fill some field, such as Autor, the app deletes all the contents of the other fields. You may fix this so the user doesn't lose all the input they've entered so far.
### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work implementing the suggested changes. 
I tested your app both locally and online but I was unable to create a book. Below is the error I ran into in the console.
```javascript
Uncaught TypeError: library is undefined
    render http://127.0.0.1:5500/app.js:92
    <anonymous> http://127.0.0.1:5500/app.js:107
```
Please fix that error and resubmit for another review.


### Martin Afani

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Change required❌

# 👋 team, 

* [ ] The issue raised earlier, is still not corrected on the live let us address it.
Screenshot from 2021-03-04 04-49-39

* [ ] Let us get rid of commented codes

**[Optional]**

* [ ] It would be better to have the pages range from 1 infinity, currently the field accepts negative values

#### That is it, kindly make the changes and submit a re-review💪.

#### Happy coding👨‍💻

Addo Forison

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Change Required
**Hello team, you have done a great job implementing the suggested changes**

### One more thing before the project can be approved
- [ ] Kindly remove the alert messages and instead, use a custom message. Alert messages are not recommended as they may block the page content as well as slow down the program.
Screenshot from 2021-03-04 16-33-10


Kindly implement the above changes before submitting another code review.
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
## HAPPY CODING 
_Slack: Oloo Moses_

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @Davidosky007 ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
